/// Flutter icons MandiriPlanIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MandiriPlanIcon
///      fonts:
///       - asset: fonts/MandiriPlanIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MandiriPlanIcon {
  MandiriPlanIcon._();

  static const _kFontFam = 'MandiriPlanIcon';

  static const IconData credit_card = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData debit_card = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData online_payment__1_ = const IconData(0xe803, fontFamily: _kFontFam);
}
